# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LottoMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LottoMate
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  

  target 'LottoMateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LottoMateUITests' do
    # Pods for testing
  end

end
